### ISSUE TITLE
Clean up dependencies

### ISSUE THREAD

**Issue by lars-sh** [Hapag-Lloyd/oversigt#40]
The following shows the result of the Maven Dependency Plugin. We should think about each of the listed dependencies and if we really need that dependency or if it can be removed.

In case we really need a dependency, it should be inserted into the POM directly or needs to be ignored for Maven Dependency Plugin reports.

### Used undeclared dependencies found:
- [x] io.atlassian.util.concurrent:atlassian-util-concurrent:jar:4.0.1
- [x] aopalliance:aopalliance:jar:1.0
- [x] javax.validation:validation-api:jar:2.0.1.Final
- [x] org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.1.Final
- [x] com.atlassian.httpclient:atlassian-httpclient-library:jar:2.0.0-m1
- [x] com.atlassian.httpclient:atlassian-httpclient-api:jar:2.0.0-m1
- [x] com.atlassian.sal:sal-api:jar:3.0.7
- [x] org.jboss.xnio:xnio-api:jar:3.3.8.Final
- [x] com.fasterxml.jackson.core:jackson-databind:jar:2.9.9
- [x] com.atlassian.jira:jira-rest-java-client-api:jar:5.1.0
- [x] org.jboss.spec.javax.annotation:jboss-annotations-api_1.2_spec:jar:1.0.2.Final
- [x] com.fasterxml.jackson.core:jackson-annotations:jar:2.9.5
- [x] org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec:jar:1.0.0.Final
- [x] org.codehaus.jettison:jettison:jar:1.1
- [x] com.atlassian.event:atlassian-event:jar:3.0.0
- [x] org.apache.commons:commons-lang3:jar:3.4
- [x] com.fasterxml.jackson.core:jackson-core:jar:2.9.5
- [x] commons-io:commons-io:jar:2.6
- [x] io.swagger:swagger-models:jar:1.5.21
- [x] io.swagger:swagger-annotations:jar:1.5.21
- [x] io.swagger:swagger-core:jar:1.5.21

### Unused declared dependencies found:
- [x] com.hlag.oversigt:oversigt-ui:jar:0.6-SNAPSHOT
- [x] org.hibernate.validator:hibernate-validator-annotation-processor:jar:6.0.13.Final
- [x] org.glassfish.web:javax.el:jar:2.2.6
- [x] org.jboss.resteasy:resteasy-client:jar:3.6.1.SP2
- [x] org.jboss.resteasy:resteasy-links:jar:3.6.1.SP2
- [x] org.jboss.resteasy:resteasy-jackson2-provider:jar:3.6.1.SP2
- [x] javax.el:javax.el-api:jar:3.0.0
- [x] com.google.inject.extensions:guice-multibindings:jar:4.2.1
- [x] io.atlassian.fugue:fugue:jar:4.7.2
- [x] commons-net:commons-net:jar:3.6

**Comment by noxone** [comment]
The following "unused" dependencies are indirectly required by other libraries:
- All dependencies with group id `org.jboss.resteasy` are required for the rest API to work.
- The hibernate validator is required for the rest API validation to work.
- Both `javax-el` dependencies are also required by the rest API.
- Atlassian fugue is required by our Jira client.

The UI package only contains resources loaded by our web server. Maybe we should change the code so that we use these resources by calling some classes from that package. Maybe we can create a dummy class that knows exactly where to find our resources so Oversigt does not need to know how the resources in a dependency works...

**Comment by noxone** [comment]
`org.jboss.xnio:xnio-api:jar:3.3.8.Final` needs to be suppressed

**Comment by noxone** [comment]
can this be closed now?
