### ISSUE TITLE
Config: Restart all event sources

### ISSUE THREAD

**Issue by lars-sh** [Hapag-Lloyd/oversigt#71]
In case of service disruptions we need to restart a bunch of even sources. That could be simplified by a "restart all" button or maybe a "restart all shown" button that even respects the current filter.

**Comment by noxone** [comment]
In configuration UI under "System" -> "Server": There is at least a section to _stop_ and _start_ all event sources. Do you want this to be extended?
Or do you think about a restart button placed in the dashoards' configuration pages so that the owner of a dashboard is able to restart all event sources included in his dashboard?

**Comment by lars-sh** [comment]
That's all I need, thanks!
